import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo Users
 */
public class FormNilai extends javax.swing.JFrame {
   public Connection getKoneksi() {
    Connection koneksi = null;
    try {
        String url = "jdbc:mysql://localhost:3306/nilai"; // Pastikan nama DB benar
        String user = "root";
        String pass = "";
        koneksi = DriverManager.getConnection(url, user, pass);
    } catch (Exception e) {
        System.out.println("Koneksi gagal: " + e.getMessage());
    }
    return koneksi;
}
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormNilai.class.getName());

    /**
     * Creates new form FormNilai
     */
    public FormNilai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        simpanTF = new java.awt.Button();
        cariTF = new java.awt.Button();
        updateTF = new java.awt.Button();
        hapusTF = new java.awt.Button();
        clearTF = new java.awt.Button();
        namaTF = new java.awt.TextField();
        nimTF = new java.awt.TextField();
        nilai1TF = new java.awt.TextField();
        nilai2TF = new java.awt.TextField();
        rataTF = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setText("Nama");

        label2.setText("Nim");

        label3.setText("Nilai1");

        label4.setText("Nilai2");

        label5.setText("Rata");

        simpanTF.setLabel("Simpan");
        simpanTF.addActionListener(this::simpanTFActionPerformed);

        cariTF.setLabel("Cari");
        cariTF.addActionListener(this::cariTFActionPerformed);

        updateTF.setLabel("Update");
        updateTF.addActionListener(this::updateTFActionPerformed);

        hapusTF.setLabel("Hapus");
        hapusTF.addActionListener(this::hapusTFActionPerformed);

        clearTF.setLabel("Clear");
        clearTF.addActionListener(this::clearTFActionPerformed);

        namaTF.setText("textField6");

        nimTF.setText("textField7");

        nilai1TF.setText("textField8");

        nilai2TF.setText("textField9");

        rataTF.setText("textField10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cariTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nimTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rataTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nilai2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nilai1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(updateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simpanTF, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nimTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nilai1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nilai2TF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rataTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(simpanTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cariTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanTFActionPerformed
    try {
        Connection kon = getKoneksi(); // Memanggil method di atas
        
        if (kon != null) {
            String sql = "INSERT INTO datanilai VALUES (?,?,?,?,?)";
            PreparedStatement ps = kon.prepareStatement(sql);
            
            ps.setString(1, nimTF.getText());
            ps.setString(2, namaTF.getText());
            ps.setString(3, nilai1TF.getText());
            ps.setString(4, nilai2TF.getText());
            ps.setString(5, rataTF.getText());

    ps.executeUpdate();

   JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        } else {
            JOptionPane.showMessageDialog(null, "Koneksi Database Gagal!");
        }
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error Simpan: " + e.getMessage());
        }
    }//GEN-LAST:event_simpanTFActionPerformed

    private void hapusTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusTFActionPerformed
                                       
    // Konfirmasi dulu sebelum hapus supaya tidak tidak sengaja terhapus
    int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data ini?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
        try {
            java.sql.Connection kon = getKoneksi(); // Memanggil method koneksi yang sudah kita perbaiki tadi
            
            // SQL untuk menghapus berdasarkan NIM
            String sql = "DELETE FROM datanilai WHERE nim = ?";
            java.sql.PreparedStatement ps = kon.prepareStatement(sql);
            
            // Mengambil NIM dari textfield sebagai acuan hapus
            ps.setString(1, nimTF.getText());
            
            int hasil = ps.executeUpdate();
            
            if (hasil > 0) {
                javax.swing.JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                // Panggil method kosongkanForm jika kamu sudah membuatnya
                nimTF.setText("");
                namaTF.setText("");
                nilai1TF.setText("");
                nilai2TF.setText("");
                rataTF.setText("");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Data dengan NIM tersebut tidak ditemukan");
            }
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Gagal Hapus: " + e.getMessage());
        }
    }
     // TODO add your handling code here:
    }//GEN-LAST:event_hapusTFActionPerformed

    private void cariTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTFActionPerformed
                                   
    try {
        java.sql.Connection kon = getKoneksi();
        // SQL untuk mencari data berdasarkan NIM
        String sql = "SELECT * FROM datanilai WHERE nim = ?";
        java.sql.PreparedStatement ps = kon.prepareStatement(sql);
        
        ps.setString(1, nimTF.getText()); // Ambil NIM dari kotak input sebagai kunci pencarian
        java.sql.ResultSet rs = ps.executeQuery();
        
        if (rs.next()) {
            // Jika data ditemukan, masukkan ke dalam TextField masing-masing
            namaTF.setText(rs.getString("nama")); // "nama" adalah nama kolom di tabel kamu
            nilai1TF.setText(rs.getString("nilai1"));
            nilai2TF.setText(rs.getString("nilai2"));
            rataTF.setText(rs.getString("rata"));
            
            javax.swing.JOptionPane.showMessageDialog(null, "Data Ditemukan!");
        } else {
            // Jika data tidak ada
            javax.swing.JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
            // Kosongkan form selain NIM jika perlu
            namaTF.setText("");
            nilai1TF.setText("");
            nilai2TF.setText("");
            rataTF.setText("");
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Gagal Cari: " + e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_cariTFActionPerformed

    private void updateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTFActionPerformed
                                        
    try {
        java.sql.Connection kon = getKoneksi();
        // SQL: Mengubah data Nama, Nilai1, Nilai2, dan Rata berdasarkan NIM sebagai kunci
        String sql = "UPDATE datanilai SET nama=?, nilai1=?, nilai2=?, rata=? WHERE nim=?";
        
        java.sql.PreparedStatement ps = kon.prepareStatement(sql);
        
        // Urutan ps.set harus sama dengan urutan di dalam perintah SQL di atas!
        ps.setString(1, namaTF.getText());   // nama=?
        ps.setString(2, nilai1TF.getText()); // nilai1=?
        ps.setString(3, nilai2TF.getText()); // nilai2=?
        ps.setString(4, rataTF.getText());   // rata=?
        ps.setString(5, nimTF.getText());    // WHERE nim=?

        int hasil = ps.executeUpdate();
        
        if (hasil > 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Data Berhasil Diperbarui!");
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Gagal Update: NIM tidak ditemukan.");
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error Update: " + e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTFActionPerformed

    private void clearTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTFActionPerformed
                                       
    try {
        java.sql.Connection kon = getKoneksi();
        // SQL: Mengubah data Nama, Nilai1, Nilai2, dan Rata berdasarkan NIM sebagai kunci
        String sql = "UPDATE datanilai SET nama=?, nilai1=?, nilai2=?, rata=? WHERE nim=?";
        
        java.sql.PreparedStatement ps = kon.prepareStatement(sql);
        
        // Urutan ps.set harus sama dengan urutan di dalam perintah SQL di atas!
        ps.setString(1, namaTF.getText());   // nama=?
        ps.setString(2, nilai1TF.getText()); // nilai1=?
        ps.setString(3, nilai2TF.getText()); // nilai2=?
        ps.setString(4, rataTF.getText());   // rata=?
        ps.setString(5, nimTF.getText());    // WHERE nim=?

        int hasil = ps.executeUpdate();
        
        if (hasil > 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Data Berhasil Diperbarui!");
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Gagal Update: NIM tidak ditemukan.");
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error Update: " + e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_clearTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormNilai().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button cariTF;
    private java.awt.Button clearTF;
    private java.awt.Button hapusTF;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.TextField namaTF;
    private java.awt.TextField nilai1TF;
    private java.awt.TextField nilai2TF;
    private java.awt.TextField nimTF;
    private java.awt.TextField rataTF;
    private java.awt.Button simpanTF;
    private java.awt.Button updateTF;
    // End of variables declaration//GEN-END:variables
}
